name: Deploy FastAPI to jquiroz.net

on:
  push:
    branches:
      - master

  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy and Run FastAPI
      run: |
        ssh -o StrictHostKeyChecking=no gerardo@jquiroz.net << 'EOF'
          cd /home/gerardo/DespliegueContinuo/productos-fastapi/productos-fastapi
          git pull origin master
          source /home/gerardo/productos-api/entorno/bin/activate
          pip install -r requeriments.txt || pip install fastapi uvicorn

          fuser -k 3013/tcp || true
          nohup /home/gerardo/productos-api/entorno/bin/uvicorn main:app --host 0.0.0.0 --port 3013 > fastapi.log 2>&1 &
        EOF
