name: Despliegue automático

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Subir archivos al servidor
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "~/api-productos-fastapi"

    - name: Instalar dependencias y ejecutar FastAPI
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/api-productos-fastapi
          pip install --user -r requirements.txt
          pkill -f "uvicorn main:app" || true
          nohup ~/.local/bin/uvicorn main:app --host 0.0.0.0 --port 3013 --reload &
